{{- $_ := required "Namespace is required" .Release.Namespace }}
{{- $_ := required "Name of Zookeeper is required." $.Values.name }}
{{- $_ := required "Zookeeper replica count is required" $.Values.replicas }}
{{- $_ := required "Docker Repository FQDN path is required" .Values.global.provider.registry.fqdn }}

apiVersion: cluster.confluent.com/v1alpha1
kind: ZookeeperCluster
metadata:
  {{- include "confluent-operator.labels" . }}
  {{- include "confluent-operator.component-name" . }}
  {{- include "confluent-operator.namespace" . }}
spec:
  replicas: {{ .Values.replicas | int }}
  image: {{ .Values.global.provider.registry.fqdn }}/{{ .Values.image.repository -}}:{{- .Values.image.tag }}
  {{- include "confluent-operator.cr-init-container" . | indent 2 }}
  terminationGracePeriodInSecond: {{ .Values.terminationGracePeriodSeconds | default 864000 }}
  {{- include "confluent-operator.cr-config-overrides" . | indent 2 }}
  jvmConfig:
    heapSize: {{ .Values.jvmConfig.heapSize }}
  {{- if .Values.global.pod }}
  {{- include "confluent-operator.cr-pod-security-config" . | indent 2 }}
  {{- end }}
  {{- if .Values.global.provider.kubernetes.clusterDomain }}
  internalKubDomain: {{ .Values.global.provider.kubernetes.clusterDomain }}
  {{- end }}
  {{- include "confluent-operator.cr-annotations" .  | indent 2 }}
  resources:
{{- include "confluent-operator.resource-requirements" . | indent 4 }}
    storage:
    {{- range $key, $value := .Values.volume }}
    - name: {{ $key }}
      capacity: {{ $value }}
    {{- end }}
  {{- if or (or .Values.nodeAffinity .Values.rack) .Values.disableHostPort }}  
  placement:
    {{- if .Values.disableHostPort }}
    disableHostPort: {{ .Values.disableHostPort }}
    {{- end }}
    {{- if .Values.nodeAffinity }}
    nodeAffinity:
      key: {{ .Values.nodeAffinity.key }}
      values:
{{ toYaml .Values.nodeAffinity.values | trim | indent 6 }}
    {{- end }}
    {{- if .Values.rack }}
    rack:
      topology: {{ .Values.rack.topology }}
    {{- end }}
  {{- end }}    
{{- if (eq (len $.Values.global.provider.kubernetes.deployment.zones) 0) }}
{{- fail "Provide atleast 1 zone information for .Values.global.provider.kubernetes.deployment.zones " }}
{{- end }}
  zones: 
{{ toYaml .Values.global.provider.kubernetes.deployment.zones | trim | indent 4 }}