{{- $_ := required "Name of controlcenter is required." $.Values.name }}
apiVersion: v1
items:
{{- range $i, $e := .Values.global.provider.kubernetes.deployment.zones }}
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    {{- include "confluent-operator.labels" $ | indent 2 }}
    annotations:
{{ toYaml $.Values.global.provider.storage.annotations | trim | indent 6 }}
    name: {{ $.Values.name }}-standard-ssd-{{ $e }}
    namespace: ""
  parameters:
{{ toYaml $.Values.global.provider.storage.parameters | trim | indent 4 }}
  provisioner: {{ $.Values.global.provider.storage.provisioner }}
  reclaimPolicy: {{ $.Values.global.provider.storage.reclaimPolicy }}
  {{- if hasKey $.Values.global.provider.storage "mountOptions" }}
  {{- if (gt (len $.Values.global.provider.storage.mountOptions) 0) }}
  mountOptions:
{{ toYaml $.Values.global.provider.storage.mountOptions | trim | indent 2 }}
  {{- end }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "volumeBindingMode" }}
  {{- if not (empty $.Values.global.provider.storage.volumeBindingMode) }}
  volumeBindingMode: {{ $.Values.global.provider.storage.volumeBindingMode }}
  {{- end }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "allowedTopologies" }}
  {{- if (gt (len $.Values.global.provider.storage.allowedTopologies)  0) }}
  allowedTopologies:
{{ toYaml $.Values.global.provider.storage.allowedTopologies | trim | indent 2 }}
  {{- end }}
  {{- end }}
{{- end }}
kind: List