apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-sslcerts
type: Opaque
{{- if and (not (empty .Values.tls.fullchain)) (not (empty .Values.tls.privkey)) }}
{{- $_ := required "Fullchain PEM cannot be empty" .Values.tls.fullchain }}
{{- $_ := required "Private key pem cannot be empty." .Values.tls.privkey }}
{{- $_ := required "Missing TLS port" .Values.tls.port }}
data:
  fullchain.pem: {{ .Values.tls.fullchain | b64enc }}
  privkey.pem: {{ .Values.tls.privkey | b64enc }}
  {{- if .Values.tls.cacerts }}
  cacerts.pem: {{ .Values.tls.cacerts | b64enc }}
  {{- end }}
{{- end }}
